variables:
  PYTHON_VERSION: "3.12"
  BASE_LAYER: bookworm-slim
  # GitLab CI creates a separate mountpoint for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy

stages:
  - test
  - deploy

default:
  image: astral/uv:python${PYTHON_VERSION}-${BASE_LAYER}
  before_script:
    - apt update
    - apt install -y build-essential curl
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source ~/.cargo/env
    - cargo install cargo-llvm-cov --locked

lint:
  stage: test
  script:
    - uv sync --group lint
    - make lint
  tags:
    - no-gpu

pytest:
  stage: test
  script:
    - uv sync --group test
    - cargo llvm-cov show-env --sh > .llvm-cov-env
    - . ./.llvm-cov-env
    - cargo llvm-cov clean --workspace
    - cargo test
    - uv run -- maturin develop --uv
    - uv run -- pytest tests --cov=src --cov-report xml
    - cargo llvm-cov report --cobertura --output-path coverage.xml
    - cargo llvm-cov report --html --output-dir htmlcov/index.html
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov/
      - coverage.xml
  tags:
    - no-gpu
    - GenuineIntel



# -----------------------------------------------------------------------------
# deploy stage
# -----------------------------------------------------------------------------

# pages:
#   stage: deploy
#   before_script:
#     - apt-get update -qq && apt-get install -y -qq make git xvfb
#     - uv sync --group docs --extra cpu
#   script:
#     - xvfb-run make document
#     - mkdir public
#     - mv docs/build/* public/
#   artifacts:
#     paths:
#       - public
#   only:
#     - main
#     - develop
#     - docs/sphinx-update
#     - update/v0.1

# .deploy:wheel:
#   stage: deploy
#   script:
#     - uv version $VERSION
#     - uv build
#     - uv publish --username __token__ --password $PYPI_PUBLISH_TOKEN -n -v

# deploy:wheel:tags:
#   image: astral/uv:python$PYTHON_VERSION-$BASE_LAYER
#   extends: .deploy:wheel
#   before_script:
#     - export VERSION=$CI_COMMIT_REF_NAME
#   only:
#     - tags
