[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "fluxel-cfd"
version = "0.2.0"
description = "An extremely fast hierarchical grid mesh generator for CFD solvers"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [{ name = "RICOS Co. Ltd." }]
maintainers = [{ name = "Daichi Ishida", email = "ishida@ricos.co.jp" }]
keywords = ["cfd", "mesh", "amr", "octree"]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Rust",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "numpy>=2.4.4",
]
[project.urls]
Repository = "https://github.com/ricosjp/fluxel"

[dependency-groups]
dev = [
    { include-group = "examples" },
    { include-group = "test" },
    { include-group = "lint" },
]
examples = [
    "pydantic",
    "pyvista",
    "pyyaml",
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-benchmark",
]
lint = ["ruff"]
docs = [
    "sphinx",
    "pydata-sphinx-theme",
    "sphinx-gallery",
    "sphinx-copybutton",
    "numpydoc",
    "sphinxcontrib-mermaid",
    "sphinx-codeautolink",
    "imageio",                            # gif animation
]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "benchmark: Run test with the --benchmark-autosave option",
]
addopts = [
    "-m",
    "not benchmark",
]

[tool.coverage.report]
ignore_errors = false
show_missing = true
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]

[tool.maturin]
bindings = "pyo3"
python-source = "src"
manifest-path = "crates/fluxel-pyo3/Cargo.toml"
module-name = "fluxel._fluxel"
include = [
    { path = "LICENSE", format = "sdist" },
    { path = "README.md", format = "sdist" },
]
