[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "fluxel"
version = "0.2.0"
description = "An extremely fast hierarchical grid mesh generator for CFD solvers"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [{ name = "RICOS Co. Ltd." }]
requires-python = ">=3.12,<3.13"
classifiers = ["Programming Language :: Python", "Programming Language :: Rust"]
dependencies = [
    "numpy>=2.4.4",
]

[dependency-groups]
dev = [
    { include-group = "examples" },
    { include-group = "test" },
    { include-group = "lint" },
]
examples = [
    "pydantic",
    "pyvista",
    "pyyaml",
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-benchmark",
]
lint = ["ruff"]
docs = [
    "sphinx",
    "pydata-sphinx-theme",
    "sphinx-gallery",
    "sphinx-copybutton",
    "numpydoc",
    "sphinxcontrib-mermaid",
    "sphinx-codeautolink",
    "imageio",                            # gif animation
]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "benchmark: Run test with the --benchmark-autosave option",
]
addopts = [
    "-m",
    "not benchmark",
]

[tool.coverage.report]
ignore_errors = false
show_missing = true
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]

[tool.maturin]
bindings = "pyo3"
python-source = "src"
manifest-path = "crates/fluxel-pyo3/Cargo.toml"
module-name = "fluxel._fluxel"
