[package]
name = "fluxel-ibm"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
# Fluxel crates
fluxel-core = { path = "../fluxel-core" }
fluxel-sfc = { path = "../fluxel-sfc" }
fluxel-geometry = { path = "../fluxel-geometry" }

# Threading libraries
rayon.workspace = true
# Spatial collision detection libraries
parry3d-f64.workspace = true
# Linear algebra libraries
nalgebra = "0.34.2"
# IO libraries
stl_io = "0.10.0"
wavefront_obj = "11.0.0"

[dev-dependencies]
tempfile.workspace = true
parry3d-f64.workspace = true
