[package]
name = "fluxel-pyo3"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
# Fluxel crates
fluxel-geometry = { path = "../fluxel-geometry" }
fluxel-ibm = { path = "../fluxel-ibm" }
fluxel-mesh = { path = "../fluxel-mesh" }
fluxel-engine = { path = "../fluxel-engine", features = ["mesh-io"] }

# Python bindings
pyo3 = { version = "0.28.2", features = ["abi3-py39", "extension-module"] }

# NumPy bindings
numpy = "0.28.0"
